// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("sdpeval")>]
[<assembly: AssemblyDescriptionAttribute("Evaluate WSUS Software Distribution Package applicability rules as defined in WSUS XML Schema Reference [https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb972752(v=vs.85)].")>]
[<assembly: AssemblyProductAttribute("sdpeval")>]
[<assembly: AssemblyCompanyAttribute("github/trondr")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © github/trondr 2019")>]
[<assembly: AssemblyVersionAttribute("1.0.19112.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.19112.1")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: GuidAttribute("59f9fa7c-b4a9-422c-8c52-958bbd1c6688")>]
[<assembly: InternalsVisibleToAttribute("spdeval.tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "sdpeval"
    let [<Literal>] AssemblyDescription = "Evaluate WSUS Software Distribution Package applicability rules as defined in WSUS XML Schema Reference [https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb972752(v=vs.85)]."
    let [<Literal>] AssemblyProduct = "sdpeval"
    let [<Literal>] AssemblyCompany = "github/trondr"
    let [<Literal>] AssemblyCopyright = "Copyright © github/trondr 2019"
    let [<Literal>] AssemblyVersion = "1.0.19112.1"
    let [<Literal>] AssemblyFileVersion = "1.0.19112.1"
    let [<Literal>] ComVisible = false
    let [<Literal>] Guid = "59f9fa7c-b4a9-422c-8c52-958bbd1c6688"
    let [<Literal>] InternalsVisibleTo = "spdeval.tests"
